// Types for the pre-bundled api/_data.js (generated by scripts/gen-api-data.mjs).
// Avoids @ts-expect-error on the JS import (playbook §7B/§7D).
import type {
  Hotel,
  Destination,
  Experience,
  HotelQuery,
  AdminStats,
} from "@aurelia/data";

export const HOTELS: Hotel[];
export const DESTINATIONS: Destination[];
export const EXPERIENCES: Experience[];
export function searchHotels(query?: HotelQuery): Hotel[];
export function getHotelById(id: string): Hotel | undefined;
export function computeAdminStats(extraBookings?: number, extraRevenue?: number): AdminStats;
